use_frameworks!

platform :ios, '8.0'

target 'KWCategoriesLib_Example' do
  pod 'KWCategoriesLib', :path => '../'

  target 'KWCategoriesLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
